---
title: "Homework 6"
author: "Shane"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



# Problem 1

## import data

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv", na = c("", "NA", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    victim_age = as.numeric(victim_age),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved",
    )
  ) %>% 
  filter(
    city_state != "Tulsa_AL", 
    victim_race %in% c("White", "Black")
  ) %>% 
  select(city_state, resolution, victim_age, victim_race, victim_sex)
```

## start with one city.

```{r}
baltimore_df =
  homicide_df %>% 
  filter(city_state == "Baltimore_MD") %>% 
  mutate(resolution = as_factor(resolution))

glm(resolution ~ victim_age + victim_race + victim_sex, 
    data = baltimore_df,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3)
```

## try this across cities.

```{r}
models_results_df = 
  homicide_df %>% 
  mutate(resolution = as_factor(resolution)) %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = 
      map(.x = data, ~glm(resolution ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())),
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state, results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI")) 
```

## make plot

```{r}
models_results_df %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```



# Problem 2

## load data and set factors

```{r}
baby_df = 
  read_csv("./data/birthweight.csv") %>% 
  mutate(
    babysex = factor(babysex, labels = c("male", "female")),
    frace = factor(frace, labels = c("White", "Black", "Asian", "Puerto Rican", "Other")),
    malform = factor(malform, labels = c("absent", "present")),
    mrace = factor(mrace, labels = c("White", "Black", "Asian", "Puerto Rican"))
  )
```

```{r}
model_fit_1 = lm(bwt ~ gaweeks, data = baby_df)

baby_df %>% 
  add_predictions(model_fit_1) %>% 
  add_residuals(model_fit_1) %>% 
  ggplot(aes(x = pred, y = resid)) + 
  geom_point()
```

```{r}
model_fit_2 = lm(bwt ~ blength + gaweeks, data = baby_df)

model_fit_3 = lm(bwt ~ blength * bhead * babysex, data = baby_df)
```


